---
- hosts: leaf01,spine01,spine02
  become: yes
  tasks:
    - name: Enable Quagga Zebra
      lineinfile:
        dest: /etc/quagga/daemons
        line: "zebra=yes"
        regexp: "zebra="
      notify: restart quagga service

    - name: Enable Quagga OSPF
      lineinfile:
        dest: /etc/quagga/daemons
        line: "ospfd=yes"
        regexp: "ospfd="
      notify: restart quagga service

    - name: Copy Interfaces File
      copy:
        src: roles/{{ansible_hostname}}/interfaces
        dest: /etc/network/interfaces
        validate: ifup -a -s -i %s
      notify: apply interface changes

    - name: Copy Routing Configuration
      copy:
        src: roles/{{ansible_hostname}}/Quagga.conf
        dest: /etc/quagga/Quagga.conf
        validate: vtysh -C -f %s
      notify: apply quagga config

  handlers:
    - name: restart quagga service
      service:
        name: quagga
        state: restarted

    - name: apply interface changes
      service:
        name: networking
        state: reloaded

    - name: apply quagga config
      service:
        name: quagga
        state: reloaded
